language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
env:
  - PACKAGES="django==1.11"
before_install:
  - pip install -q $PACKAGES
install:
  - pip install -r test_requirements.txt
script:
  - python setup.py test
